
-- Basic
dofile(elepm.modpath.."/machines/bases/init.lua")
dofile(elepm.modpath.."/machines/accumulator.lua")
dofile(elepm.modpath.."/machines/furnace.lua")
dofile(elepm.modpath.."/machines/alloy_furnace.lua")
dofile(elepm.modpath.."/machines/coal_alloy_furnace.lua")
dofile(elepm.modpath.."/machines/pulverizer.lua")
dofile(elepm.modpath.."/machines/grindstone.lua")
dofile(elepm.modpath.."/machines/sawmill.lua")
dofile(elepm.modpath.."/machines/generator.lua")
dofile(elepm.modpath.."/machines/storage.lua")
dofile(elepm.modpath.."/machines/lava_cooler.lua")
dofile(elepm.modpath.."/machines/solderer.lua")
dofile(elepm.modpath.."/machines/lava_generator.lua")
dofile(elepm.modpath.."/machines/steam_turbine.lua")
